### ISSUE TITLE
Open Rate

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#18]
![Open_Rate](https://user-images.githubusercontent.com/16281246/55740429-11b03480-59f9-11e9-8b59-b01ff0ce50b0.png)

**API Calls Used**
`/api/v2/accounts/{account_id}/reports/bulletins/summary`

**Data Needed:**
- (a) `opens_count`÷`total_delivered` between the user-defined `start_date` and `end_date` (which we are assuming, unless told otherwise, will be a week. 
- (b) `opens_count`÷`total_delivered` week before the user-defined `start_date` and `end_date`
- (c) `opens_count`÷`total_delivered` 2 weeks before the user-defined `start_date` and `end_date` 

- % Difference b/w (a) & (b)
- % Difference b/w (a) & (c)

**Comment by omerbensaadon** [comment]
Following up to see whether `open_count` is unique opens or not

**Comment by omerbensaadon** [comment]
Product Owner (Anthony) stated that `open_rate` does mean unique open rate, based on his prior experience.

**Comment by omerbensaadon** [comment]
To be calculated in Tableau

**Comment by loganpowell** [comment]
Got this working, but this type of derived field/row cannot be appended to the existing Bulletins table/schema due to the fact that these values are `float`s and the bulletins schema are `int`s (integers).

I had to create a separate schema/table and add it there
![granicus-Rates-1](https://user-images.githubusercontent.com/3408191/56304459-246aed80-610c-11e9-80d7-d07f66078984.PNG)

**Comment by omerbensaadon** [comment]
Honestly, that'll work just fine. 

We can parse these out into a separate sheet as we currently are.
