### ISSUE TITLE
Subscribers + Engagement Rate Per Topic

### ISSUE THREAD

**Issue by omerbensaadon** [uscensusbureau/granicus#47]
<img width="329" alt="Screen Shot 2019-04-16 at 8 11 47 AM" src="https://user-images.githubusercontent.com/16281246/56209480-a9c5a380-6021-11e9-99ab-9d667a3dc29e.png">

**API Calls Used**
(1) `/api/v2/accounts/{account_id}/reports/topics/{id}`
(2) `/api/v2/accounts/{account_id}/topics/{id}/engagement_rate`

**Data Needed:**
- (a)  (1) `name` + `total_subscriptions_to_date` and (2) `engagement_rate` for the week ending in the user-defined `end_date` 
- (b)  (1) `name` + `total_subscriptions_to_date` and (2) `engagement_rate` for the week before the user-defined `end_date`
- (c) (1) `name` + `total_subscriptions_to_date` and (2) `engagement_rate` for the week 2 weeks before the user-defined `end_date` 

**Topic ID's Needed:**
- [x] General 2020 Census Updates | **289016**

- [x] America Counts: Stories Behind the Numbers | **449122**

- [x] Census Academy | **454831**

- [x] Census Jobs | **449126**

- [x] Census Partnerships | **452433**

- [x] Census Updates | **444983**

- [x] Census Updates for Business | **444992**

- [x] Data Visualization Newsletter | **447782**

- [x] Statistics in Schools | **449124**

- [x] Stats for Stories | **452958**

**Tableau Data Format:**
- Columns: Topic Names +  Each week of data (This Week, Previous Week, Three Weeks Ago)

- Rows: As shown in Excel sheet above. Topic Subscribers + Engagement rate alternating for each respective topic.

**Note:**
The `{id}` mentioned in the call is reflected by the bold numbers written above.

**Comment by loganpowell** [comment]
Two things here:

1. I'm not sure if it's due to my key being limited in permissions, but I'm only able to see the `State Data Center Leads` topic, even if I make the time range in my request go back to last year.
2. The actual `{id}` used by Granicus' API isn't the `USCENSUS_...` code but another code that is made up of (at least in the case of State Data Center Leads) a 5-digit numeric id. 

We'll have to look into these together in our next meeting. We can elevate my key or use a different one to test for 1. Once I'm able to get all the actual IDs, I can make the calls for 2

**Comment by loganpowell** [comment]
Also, I'm labeling this a `M` because the logic for fetching and combining the data will be different given I'll have to make an array of calls for each column (each time window). I'm not optimistic about being able to do this without timeouts after my experience with https://github.com/uscensusbureau/granicus/issues/31#issuecomment-486339530

**Comment by loganpowell** [comment]
I've got the functionality for this working now, but I'm still only able to see the single id for State Data Center Leads.

I'm going to leave this open until we get the list of IDs I need to populate the actual calls. I'll also follow up with Richard on this.

**Comment by loganpowell** [comment]
I also changed this to an `L` as it was a huge PITA to traverse through an array of arrays of API calls and reduce them into their usable format. Labeling change for future reference if any other features need something similar.

**Comment by loganpowell** [comment]
This is done

**Comment by loganpowell** [comment]
Just ran into a snag. Though everything works in the simulator, I'm getting an error on Tableau desktop. I'll have to debug it on Wednesday.

**Comment by omerbensaadon** [comment]
Ask Ryan what the best way to input this data is.

1. Only 1 table, all subscriber count (integers) and engagement rate (%) will return as floats
2.  Create 2 Tables, one for engagement rate (%) one for subscriber count (integers) add a common column (Topic Name, ID, ETC.) use  a join
3. 2 Separate tables. No common column to use for a join (i.e. unjoinable)

**Comment by omerbensaadon** [comment]
Ryan says the best option is #2 for the above options

**Comment by loganpowell** [comment]
Got this working on Tableau Desktop. From the above options, #1 is currently in the working WDC

**Comment by omerbensaadon** [comment]
I'm moving this to in progress! 

Move it to done once #2 is finished?

**Comment by loganpowell** [comment]
Debugging complete.
